cookbook "apt"
cookbook "locales"
cookbook "timezone-ii"
cookbook "ntp"
cookbook "vim"
cookbook "nano"
cookbook "curl"	
cookbook "java"
cookbook "maven"
cookbook "gradle"
cookbook "nodejs"
cookbook "golang"
cookbook "mongodb"
cookbook "rvm", github: "fnichol/chef-rvm"